package com.rabbitmq.main;

import com.rabbitmqUntil.RabbitmqUtil;
import org.junit.Test;

public class RabbitmqMain {

    public static void main(String[] args) {
        RabbitmqUtil rabbitmqUtil = new RabbitmqUtil();
        rabbitmqUtil.send("<PLAYLIST>" +
                "<DEVICEID>22830001</DEVICEID>" +
                "<DEVICEWIDTH>128</DEVICEWIDTH>" +
                "<DEVICEHEIGHT>64</DEVICEHEIGHT>" +
                "<PLAYITEM>" +
                "  <DELAYTIME>3</DELAYTIME>" +
                "  <TRANSTION>1</TRANSTION>" +
                "  <SPEED>0</SPEED>" +
                "  <FONTSIZE>32</FONTSIZE>" +
                "  <FONTFAMILY>s</FONTFAMILY>" +
                "  <FONTCOLOR>000000000255</FONTCOLOR>" +
                "  <FONTBACKGROUND></FONTBACKGROUND>" +
                "  <FONTDISTANCE>0</FONTDISTANCE>" +
                "  <ICONCONTENT>" +
                "     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>" +
                "  </ICONCONTENT>" +
                "  <TEXTCONTENT>" +
                "     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>" +
                "     <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>" +
                "  </TEXTCONTENT>" +
                "  </PLAYITEM>" +
                "  <PLAYITEM>" +
                "  <DELAYTIME>3</DELAYTIME>" +
                "  <TRANSTION>1</TRANSTION>" +
                "  <SPEED>0</SPEED>" +
                "  <FONTSIZE>32</FONTSIZE>" +
                "  <FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>" +
                "  <FONTBACKGROUND></FONTBACKGROUND>" +
                "  <FONTDISTANCE>0</FONTDISTANCE>" +
                "  <ICONCONTENT>" +
                "    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>" +
                "  </ICONCONTENT>" +
                "  <TEXTCONTENT>" +
                "    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>" +
                "    <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>" +
                "  </TEXTCONTENT>" +
                "</PLAYITEM>" +
                "</PLAYLIST>" +
                 "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>"  +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>"+
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>"  +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>"+
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>"  +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>" +
                "<PLAYLIST><DEVICEID>22830001</DEVICEID><DEVICEWIDTH>128</DEVICEWIDTH><DEVICEHEIGHT>64</DEVICEHEIGHT><PLAYITEM> " +
                " <DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE> " +
                " <FONTFAMILY>s</FONTFAMILY>  <FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>     <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B03</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>     <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">安全</TEXT>     " +
                "<TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">驾驶</TEXT>  </TEXTCONTENT>  </PLAYITEM>  <PLAYITEM>  " +
                "<DELAYTIME>3</DELAYTIME>  <TRANSTION>1</TRANSTION>  <SPEED>0</SPEED>  <FONTSIZE>32</FONTSIZE>  " +
                "<FONTFAMILY>s</FONTFAMILY><FONTCOLOR>000000000255</FONTCOLOR>  <FONTBACKGROUND></FONTBACKGROUND> " +
                " <FONTDISTANCE>0</FONTDISTANCE>  <ICONCONTENT>    <ICON LEFT=\\\"0\\\" TOP=\\\"0\\\">B04</ICON>  " +
                "</ICONCONTENT>  <TEXTCONTENT>    <TEXT LEFT=\\\"64\\\" TOP=\\\"0\\\">平安</TEXT>   " +
                " <TEXT LEFT=\\\"64\\\" TOP=\\\"32\\\">回家</TEXT>  </TEXTCONTENT></PLAYITEM></PLAYLIST>");
        rabbitmqUtil.receive();
    }

    /**
    * 发送测试
    */
    @Test
    public void  queueSendTest(){
        RabbitmqUtil rabbitmqUtil = new RabbitmqUtil();
        rabbitmqUtil.send("Hello RabbitMQ");
        //rabbitmqUtil.receive();
       }

}
